"""Init medical sports schema

Revision ID: c3999c6ed0ca
Revises: 
Create Date: 2026-04-22 08:28:46.931938+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision: str = 'c3999c6ed0ca'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto;")
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rag_execution_log',
    sa.Column('trace_id', sa.String(length=100), nullable=False, comment='Langfuse Trace ID와 매핑'),
    sa.Column('user_query', sa.Text(), nullable=False),
    sa.Column('intent', sa.String(length=50), nullable=False),
    sa.Column('raw_generation', sa.Text(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=True, comment='Guardrails/PostCheck 통과 여부'),
    sa.Column('error_type', sa.String(length=50), nullable=True),
    sa.Column('error_reason', sa.Text(), nullable=True),
    sa.Column('diagnostics', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='소요 시간, 검색된 청크 ID 등 메타데이터'),
    sa.Column('is_security_alert', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='rag_execution_log table'
    )
    op.create_index(op.f('ix_rag_execution_log_trace_id'), 'rag_execution_log', ['trace_id'], unique=True)
    op.create_table('source_chunk',
    sa.Column('content', sa.Text(), nullable=False, comment='청크 텍스트'),
    sa.Column('content_hash', sa.String(length=64), sa.Computed("encode(digest(coalesce(content,''), 'sha256'), 'hex')", persisted=True), nullable=False, comment='자동 생성 SHA256'),
    sa.Column('chunk_tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('simple', coalesce(content,''))", persisted=True), nullable=False, comment='Native FTS용 TSVECTOR'),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_version', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='증분 업데이트용 Soft Delete 플래그'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_hash', 'chunk_index', 'chunk_version', name='uq_source_chunk_content_hash_chunk_index_chunk_version')
    )
    op.create_index('ix_source_chunk_chunk_tsv_gin', 'source_chunk', ['chunk_tsv'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_source_chunk_is_active'), 'source_chunk', ['is_active'], unique=False)
    op.create_table('source_clinical_guideline',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('issuing_body', sa.String(length=100), nullable=False, comment='발행 기관 (예: ACSM, 대한의학회)'),
    sa.Column('publication_year', sa.Integer(), nullable=False),
    sa.Column('reliability_tier', sa.String(length=20), nullable=False, comment='신뢰도 등급'),
    sa.Column('disease_category', sa.String(length=100), nullable=True),
    sa.Column('content', sa.Text(), nullable=False, comment='원본 텍스트 전체'),
    sa.Column('content_hash', sa.String(length=64), nullable=True, comment='원본 텍스트 sha256 해시'),
    sa.Column('process', sa.String(length=20), nullable=False, comment='전처리 단계 (예: parsed, chunked)'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='source_clinical_guideline table'
    )
    op.create_index(op.f('ix_source_clinical_guideline_content_hash'), 'source_clinical_guideline', ['content_hash'], unique=False)
    op.create_table('source_research_paper',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('doi', sa.String(length=100), nullable=False),
    sa.Column('authors', sa.Text(), nullable=True),
    sa.Column('journal', sa.String(length=255), nullable=True),
    sa.Column('publication_date', sa.String(length=50), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False, comment='문서 언어 (en, fr, ko)'),
    sa.Column('content', sa.Text(), nullable=False, comment='원본 텍스트 전체'),
    sa.Column('content_hash', sa.String(length=64), nullable=True, comment='원본 텍스트 sha256 해시'),
    sa.Column('process', sa.String(length=20), nullable=False, comment='전처리 단계 (예: parsed, chunked)'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='source_research_paper table'
    )
    op.create_index(op.f('ix_source_research_paper_content_hash'), 'source_research_paper', ['content_hash'], unique=False)
    op.create_index(op.f('ix_source_research_paper_doi'), 'source_research_paper', ['doi'], unique=True)
    op.create_table('map_source_chunk',
    sa.Column('chunk_id', sa.BigInteger(), nullable=False),
    sa.Column('source_id', sa.BigInteger(), nullable=False),
    sa.Column('source_name', sa.Enum('clinical_guideline', 'research_paper', name='source_name_enum'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['source_chunk.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chunk_id', 'source_id', 'source_name', name='uq_map_source_chunk_chunk_id_source_id_source_name')
    )
    op.create_index('ix_map_source_chunk_chunk_id', 'map_source_chunk', ['chunk_id'], unique=False)
    op.create_index('ix_map_source_chunk_source_id_source_name', 'map_source_chunk', ['source_id', 'source_name'], unique=False)
    op.create_table('source_chunk_vec',
    sa.Column('chunk_id', sa.BigInteger(), nullable=False),
    sa.Column('chunk_vec', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=False),
    sa.Column('vec_model_name', sa.String(length=50), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['source_chunk.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chunk_id', 'vec_model_name', name='uq_source_chunk_vec_chunk_id_vec_model_name')
    )
    op.create_index('ix_source_chunk_vec_chunk_id', 'source_chunk_vec', ['chunk_id'], unique=False)
    op.create_index('ix_source_chunk_vec_chunk_vec_hnsw', 'source_chunk_vec', ['chunk_vec'], unique=False, postgresql_using='hnsw', postgresql_ops={'chunk_vec': 'vector_cosine_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_source_chunk_vec_chunk_vec_hnsw', table_name='source_chunk_vec', postgresql_using='hnsw', postgresql_ops={'chunk_vec': 'vector_cosine_ops'})
    op.drop_index('ix_source_chunk_vec_chunk_id', table_name='source_chunk_vec')
    op.drop_table('source_chunk_vec')
    op.drop_index('ix_map_source_chunk_source_id_source_name', table_name='map_source_chunk')
    op.drop_index('ix_map_source_chunk_chunk_id', table_name='map_source_chunk')
    op.drop_table('map_source_chunk')
    op.drop_index(op.f('ix_source_research_paper_doi'), table_name='source_research_paper')
    op.drop_index(op.f('ix_source_research_paper_content_hash'), table_name='source_research_paper')
    op.drop_table('source_research_paper')
    op.drop_index(op.f('ix_source_clinical_guideline_content_hash'), table_name='source_clinical_guideline')
    op.drop_table('source_clinical_guideline')
    op.drop_index(op.f('ix_source_chunk_is_active'), table_name='source_chunk')
    op.drop_index('ix_source_chunk_chunk_tsv_gin', table_name='source_chunk', postgresql_using='gin')
    op.drop_table('source_chunk')
    op.drop_index(op.f('ix_rag_execution_log_trace_id'), table_name='rag_execution_log')
    op.drop_table('rag_execution_log')
    # ### end Alembic commands ###
